# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HeardSample' do


pod 'Alamofire', '~> 3.0'
pod 'Kingfisher', '~> 1.8'
pod 'PKHUD'
pod 'UITextView+Placeholder'

end

target 'HeardSampleTests' do

end

target 'HeardSampleUITests' do

end

